# Use a base image with Java installed
FROM openjdk:latest

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file into the container
COPY target/backend-0.0.1-SNAPSHOT.jar /app/backend-0.0.1-SNAPSHOT.jar.jar

# Expose the port your app runs on (if necessary)
EXPOSE 8080

# Command to run your application
CMD ["java", "-jar", "backend-0.0.1-SNAPSHOT.jar.jar"]
